# Timelog

* Automatic Videography of Audio Tracks of Songs
* Andrew Parker
* 2389622p
* Dubasis Gangnuly

## Week 4

### 19 Oct 2021

* 0.5 hrs - Setting up a GitHub repository and researching Virtual Environments

* 2 hrs - Researching packages to strip YouTube audio then creating and debugging program

* 1 hrs - Creating and debugging program to fetch the captions from a YouTube video

* 3 hrs - Creating and debugging Speech Recognition for no accessible captions on videos.

* 1 hrs - Reworking Speech Recognition and researching possible alternatives to current attempt.

* 0.5 hrs - Fixing Virtual environment caused by .gitignore when pushed to repository

## 20 Oct 2021

* 0.5hrs - Brainstormed potential ideas and investigated Librosa Library for beat extraction

* 0.5hrs - Implemented an average beat extractor using Librosa Library

* 2hrs - Researching extracting amplitudes with beats and bebugging PyGame visualisation (abandoned for now)

* 2hrs - Researching Django and integration with Firebase

* 1hrs - Attempting to set-up Git actions to automatically store changes to the Virtual Environment (unsuccessful)

* 1hrs - Attempting to create visualisation of beats

* 1hrs - Debugging SpeechRecognition (source being potentially corrupy .wav files)

* 1hrs - Reworking SpeechRecognition program function due to 1min audio limit

* 1.5hrs - Attempting to find appropraite google search api and debug search program

## 21 Oct 2021

* 0.5 hrs - Advisor Meeting

## 1 Nov 2021 

* 1 hrs - Creating Dissertation Latex file, setting up bibliography

* 1 hrs - Reading up on and creating a Django project 

* 1 hrs - Creating Django project and setting up first test pages

## 2 Nov 2021 

* 0.5 hrs - Setting up Mendeley for paper review and reviewing papers

* 1.5 hrs - Watching django tutorials and implementing django.

## 3 Nov 2021

* 2hrs - Watched tutorials for django

* 0.5hrs - Watching tutorial for and implementing bootstrap in django

* 2 hrs - Finding relevant research papers, reading reasearch papers

* 1 hrs - Implementing and testing the Genius Api, to get lyrics

* 0.5 hrs - Investigating 'forced alignment' apis for matching lyrics to audio

* 1 hrs - Reading research papers

## 4 Nov 2021

* 1 hrs - Avisor meeting and creating presentation slides

* 1 hrs - Reading research papers

## 6 Nov 2021

* 4 hrs - Integrating django and audioStripper Component

## 9 Nov 2021

* 2 hrs - Reserching and implementing forced alignment

## 10 Nov 2021

* 8 hrs - Integrating django with current components, integrated FireBase as realtime database.

## 11 Nov 2021

* 1 hrs - Working on Bing Image Search

* 0.5 hrs - Advisor Meeting

* 1.5 hrs - Passing variables between views and Bing Image Search fully implemented

## 18 November 2021

* 0.5 hrs - Advisor Meeting

## 2 Decemeber 2021

* 0.5 hrs - Advisor Meeting

* 1 hrs - trying to identify limits of the Bing Search Api 

* 2 hrs - Researching the scraping of images from Wikipedia

## 9 December 2021

* 0.5 hrs - Advisor Meeting


## 11 December 2021

* 3 hrs - Implementing a scaping tool for images from Wikipedia which align with keywords

* 2 hrs - Further work into extrcating images from sections of web page specific to Wikipedia

## 12 Decemeber 2021 

* 2 hrs - Implementing a keyword extracting form the transcripts


# 3 January 2022

* 0.5 hrs - Designed way to determine timestamp from lyric video

* 3 hrs - Creating a system to analyse and record the text found on lyric video using pytesseract

* 0.5 hrs - Contacting individuals for access to an english langauge model for forced alignment


## 4 January 2022

* 2 hrs - Rework audioStripper to now download the entire youtube video and seperate audio

* 1 hrs - Incorporated errors to be displayed in Django forms

## 5 January 2022

* 3 hrs - Debugging passing multiple forms from a django webpage

* 0.5 hrs - Finalising index.html 

## 6 January 2022

* 0.25 hrs - creating error message for caption fetcher

## 7 January 2022

* 1 hrs - Creating generic keyword extractor for.txt file

* 1 hrs - Scraping Wikipedia for google imaegs scraping

## 8 January 2022

* 2 hrs - Looking into emojis as replacement for pngs

* 4 hrs - Working on debugging stitching images together for videos

## 9 January 2022

* 2 hrs - Contiuing working on google image Scraper 

* 2 hrs - Reaserching moviepy's method of stringing images together (and making prototype)

## 10 January 2022

* 2 hrs - Creating logic for timing of image placement 

* 2 hrs - Creating generic video generator from produced timings

* 2 hrs - Debugging video generator 

## 11 January 2022

* 2 hrs - Debugging video generator 

* 0.5 hrs - Integrating image generator into project

## 12 January 2022

* 0.5 hrs - Debugging video displaying on webpage

* 0.5 hrs - Debugging adding audio to video

* 1 hrs - Debugging youtubeId with punctuation causing errors

## 13 January 2022

* 1 hrs - Meeting and meeting prep

## 19 January 2022

* 0.5 hrs - Looking into Firebase security

* 3 hrs - Integrating lyric video logic into Django (incomplete)

# 20 January 2022

* 1 hrs - Meeting and meeting prep

# 21 January 2022

* 0.5 hrs - Reasearching new forced alignment tool

* 3 hrs - Attempting to install Singularity to use tool

* 1 hrs - Attempting to get API wrapper for alignment tool to work

# 23 January 2022

* 7 hrs - Implementing and debugging accessing alignment tool through Selenium

# 24 January 2022 

* 2 hrs - Fully implemented alignment tool for django webframe

# 25 January 2022

* 0.5 hrs - Writing documentation

* 3 hrs - Implemented collections tab for django and debugging

# 26 January 2022

* 3 hrs - Fully implementing lyric video logic and integration

* 2 hrs - Added ability to add 'buffer' to forced alignment to make images appear longer.

# 27 January 2022

* 1 hrs - Meeting and meeting prep

# 29 January

* 2 hrs - Feedback section will not error without sdk

# 3 Feburary 2022

* 1 hrs - Meeting and meeting prep

# 9 Feburary 2022

* 3 hrs - Fixing PyTube module

# 10 Feburary 2022

* 1 hrs - Meeting and meeting prep

# 16 Feburary 2022

* 4 hrs - Working on a fix for auto generated captions ebing off

# 17 Feburary 2022

* 1 hrs - Meeting and meeting prep

* 3 hrs - Writing and reasearching conference paper

# 18 Feburary 2022

* 2 hrs - Added collection support

* 3 hrs - Writing and reasearching conference paper

# 19 Feburary 2022

* 2 hrs - Updating READ.me to have accurate installation information

* 2 hs - Testing installation process

* 3 hrs - Writing and reasearching conference paper

# 20 Feburary 2022

* 2 hrs - Finding suitable canditates for video examples

* 2 hrs - Planning a user study

# 24 Feburary 2022

* 1 hrs - Meeting and meeting prep

* 2 hrs - Finding appropraite documents for participating in a user study

* 3 hrs - Drawing up user study

# 26 Feburary 2022

* 6 hrs - Reasearching and writing Dissertation

# 27 Feburary 2022

* 6 hrs - Reasearching, writing, and editting Dissertation

# 27 Feburary 2022

* 4 hrs - Reasearching, writing, and editting Dissertation

# 11 March 2022

* 6 hrs - Reasearching, writing, and editting Dissertation

# 12 March 2022

* 6 hrs - Reasearching, writing, and editting Dissertation

# 21 March 2022

* 2 hrs - Reasearching, writing, and editting Dissertation

# 22 March 2022

* 5 hrs - Reasearching, writing, and editting Dissertation

# 23 March 2022

* 6 hrs - Reasearching, writing, and editting Dissertation

# 24 March 2022

* 6 hrs - Reasearching, writing, and editting Dissertation

# 25 March 2022

* 8 hrs - Reasearching, writing, and editting Dissertation

# 26 March 2022

* 4 hrs - Reasearching, writing, and editting Dissertation

# 28 March 2022

* 4 hrs - Reasearching, writing, and editting Dissertation

# 29 March 2022

* 8 hrs - Reasearching, writing, and editting Dissertation

# 30 March 2022

* 8 hrs - Reasearching, writing, and editting Dissertation

# 31 March 2022

* 10 hrs - Reasearching, writing, and editting Dissertation












# ADD documentation about PyTube or Youtube_dl failures


