#!c:\users\andre\onedrive\desktop\workspace\dissertation\automatic-videography-of-audio-tracks-of-songs\virtualenvironment\audiovirtualenv\scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
